inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - "spec/**/*" # https://github.com/rubocop/rubocop/issues/4222

Metrics/BlockLength:
  AllowedMethods:
    - "no_commands" # thor
  Exclude:
    - "spec/**/*.rb"

Style/FetchEnvVar:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
