version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.6
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.5.1
            bundle install
            bundle exec rake
      - run:
          name: Rubocop
          command: bundle exec rubocop --format quiet
