#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.expand_path("../lib", File.dirname(__FILE__))
require File.expand_path("../lib/trello_tool_thor", File.dirname(__FILE__))

TrelloToolThor.start
